#!/bin/bash

set -e

DB_NAME="frontscale"
DB_USER="frontscale"

echo "Atualizando subscription_status para active..."

psql -U "$DB_USER" -d "$DB_NAME" <<'SQL'
UPDATE users
SET subscription_status = 'active';
SQL

echo "Atualização concluída."
