#!/bin/bash

set -e

cd /root/frontscale

git pull

pnpm install

pnpm --filter @workspace/db run migrate
pnpm --filter @workspace/frontscale run build
pnpm --filter @workspace/api-server run build

rm -rf /var/www/frontscale/*

cp -a /root/frontscale/artifacts/frontscale/dist/public/. /var/www/frontscale/

chown -R www-data:www-data /var/www/frontscale
chmod -R 755 /var/www/frontscale

systemctl reload nginx

pm2 reload all
